services:
    jupyter:
        build: .
        ports:
            - "8889:8889"
        environment:
            NAME: "World"
        volumes:
            - ./notebooks:/app/notebooks
        command:
            [
                "jupyter",
                "notebook",
                "--ip=0.0.0.0",
                "--port=8889",
                "--no-browser",
                "--allow-root",
                "--NotebookApp.notebook_dir=/app/notebooks",
            ]
